/*
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zowe_commons_attls_AttlsContextImpl */

#ifndef _Included_org_zowe_commons_attls_AttlsContextImpl
#define _Included_org_zowe_commons_attls_AttlsContextImpl
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_zowe_commons_attls_AttlsContextImpl
 * Method:    clean
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zowe_commons_attls_AttlsContextImpl_clean
  (JNIEnv *, jobject);

/*
 * Class:     org_zowe_commons_attls_AttlsContextImpl
 * Method:    getStatPolicy
 * Signature: ()Lorg/zowe/commons/attls/StatPolicy;
 */
JNIEXPORT jobject JNICALL Java_org_zowe_commons_attls_AttlsContextImpl_getStatPolicy
  (JNIEnv *, jobject);

/*
 * Class:     org_zowe_commons_attls_AttlsContextImpl
 * Method:    getStatConn
 * Signature: ()Lorg/zowe/commons/attls/StatConn;
 */
JNIEXPORT jobject JNICALL Java_org_zowe_commons_attls_AttlsContextImpl_getStatConn
  (JNIEnv *, jobject);

/*
 * Class:     org_zowe_commons_attls_AttlsContextImpl
 * Method:    getProtocol
 * Signature: ()Lorg/zowe/commons/attls/Protocol;
 */
JNIEXPORT jobject JNICALL Java_org_zowe_commons_attls_AttlsContextImpl_getProtocol
  (JNIEnv *, jobject);

/*
 * Class:     org_zowe_commons_attls_AttlsContextImpl
 * Method:    getNegotiatedCipher2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zowe_commons_attls_AttlsContextImpl_getNegotiatedCipher2
  (JNIEnv *, jobject);

/*
 * Class:     org_zowe_commons_attls_AttlsContextImpl
 * Method:    getSecurityType
 * Signature: ()Lorg/zowe/commons/attls/SecurityType;
 */
JNIEXPORT jobject JNICALL Java_org_zowe_commons_attls_AttlsContextImpl_getSecurityType
  (JNIEnv *, jobject);

/*
 * Class:     org_zowe_commons_attls_AttlsContextImpl
 * Method:    getUserId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zowe_commons_attls_AttlsContextImpl_getUserId
  (JNIEnv *, jobject);

/*
 * Class:     org_zowe_commons_attls_AttlsContextImpl
 * Method:    getFips140
 * Signature: ()Lorg/zowe/commons/attls/Fips140;
 */
JNIEXPORT jobject JNICALL Java_org_zowe_commons_attls_AttlsContextImpl_getFips140
  (JNIEnv *, jobject);

/*
 * Class:     org_zowe_commons_attls_AttlsContextImpl
 * Method:    getFlags
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_org_zowe_commons_attls_AttlsContextImpl_getFlags
  (JNIEnv *, jobject);

/*
 * Class:     org_zowe_commons_attls_AttlsContextImpl
 * Method:    getNegotiatedCipher4
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zowe_commons_attls_AttlsContextImpl_getNegotiatedCipher4
  (JNIEnv *, jobject);


/*
 * Class:     org_zowe_commons_attls_AttlsContextImpl
 * Method:    getCrtificate
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_zowe_commons_attls_AttlsContextImpl_getCertificate
  (JNIEnv *, jobject);

/*
 * Class:     org_zowe_commons_attls_AttlsContextImpl
 * Method:    initConnection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zowe_commons_attls_AttlsContextImpl_initConnection
  (JNIEnv *, jobject);

/*
 * Class:     org_zowe_commons_attls_AttlsContextImpl
 * Method:    resetSession
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zowe_commons_attls_AttlsContextImpl_resetSession
  (JNIEnv *, jobject);

/*
 * Class:     org_zowe_commons_attls_AttlsContextImpl
 * Method:    resetCipher
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zowe_commons_attls_AttlsContextImpl_resetCipher
  (JNIEnv *, jobject);

/*
 * Class:     org_zowe_commons_attls_AttlsContextImpl
 * Method:    stopConnection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zowe_commons_attls_AttlsContextImpl_stopConnection
  (JNIEnv *, jobject);

/*
 * Class:     org_zowe_commons_attls_AttlsContextImpl
 * Method:    allowHandShakeTimeout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zowe_commons_attls_AttlsContextImpl_allowHandShakeTimeout
  (JNIEnv *, jobject);



#ifdef __cplusplus
}
#endif
#endif
