name: "Build native libraries"
description: "Run the build of the libraries on targeted platform."

runs:
  using: "composite"
  steps:
    - name: install zowe/cli
      run: npm install -g @zowe/cli@6.32.2
    - name: install zowe-api-dev
      run: npm -g install @zowedev/zowe-api-dev

    - name: Build with Gradle
      run: |
        zowe profiles create ssh-profile maristzowe --host ${{ secrets.SSH_MARIST_RACF_HOST }} --port 22 --user ${{ secrets.SSH_MARIST_USERNAME }} --password ${{ secrets.SSH_MARIST_RACF_PASSWORD }}
        zowe profiles create zosmf-profile maristzowe --host ${{ secrets.SSH_MARIST_RACF_HOST }} --port 10443 --user ${{ secrets.SSH_MARIST_USERNAME }} --pass ${{ secrets.SSH_MARIST_RACF_PASSWORD }} --reject-unauthorized false
        ./gradlew :attls:zosbuild
        ./gradlew build