name: common-java

on: [pull_request]

env:
  PR_NUMBER: ${{ github.event.inputs.pull_request }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release_type: [release, snapshot]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install zowe/cli
        run: npm install -g @zowe/cli@6.32.2
      - name: install zowe-api-dev
        run: npm -g install @zowedev/zowe-api-dev

      - name: Build with Gradle
        run: |
          zowe profiles create ssh-profile maristzowe --host ${{ secrets.SSH_MARIST_RACF_HOST }} --port ${{ secrets.SSH_MARIST_RACF_PORT }} --user ${{ secrets.SSH_MARIST_USERNAME }} --password ${{ secrets.SSH_MARIST_RACF_PASSWORD }}
          zowe profiles create zosmf-profile maristzowe --host ${{ secrets.SSH_MARIST_RACF_HOST }} --port 10443 --user ${{ secrets.SSH_MARIST_USERNAME }} --pass ${{ secrets.SSH_MARIST_RACF_PASSWORD }} --reject-unauthorized false
          ./gradlew :attls:zosbuild
          ./gradlew build

  release:
      if: github.event_name == 'push' && github.ref_protected
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Use Node LTS
          uses: actions/setup-node@v3
          with:
            node-version: 'lts/*'
        - name: install zowe/cli
          run: npm install -g @zowe/cli@6.32.2
        - name: install zowe-api-dev
          run: npm -g install @zowedev/zowe-api-dev

        - name: Release or snapshot
          run: |
            if [ "${{matrix.release_type }}" == "snapshot" ];
            ./gradlew publish -x test -Pzowe.deploy.username=$ARTIFACTORY_USERNAME -Pzowe.deploy.password=$ARTIFACTORY_PASSWORD -Partifactory_user=$ARTIFACTORY_USERNAME -Partifactory_password=$ARTIFACTORY_PASSWORD
            else
            ./gradlew release -x test -Prelease.useAutomaticVersion=true -Pzowe.deploy.username=$ARTIFACTORY_USERNAME -Pzowe.deploy.password=$ARTIFACTORY_PASSWORD -Partifactory_user=$ARTIFACTORY_USERNAME -Partifactory_password=$ARTIFACTORY_PASSWORD
            fi
          env:
            ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
            ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
