name: Build on platform

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ZOWE_ROBOT_TOKEN }}
      - uses: ./.github/actions/native-build
        with:
          host: ${{ secrets.SSH_MARIST_RACF_HOST }}
          username: ${{ secrets.SSH_MARIST_USERNAME }}
          passwd: ${{ secrets.SSH_MARIST_RACF_PASSWORD }}
          port: ${{ secrets.SSH_MARIST_ALLSYS_PORT }}