name: common-java

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ZOWE_ROBOT_TOKEN }}
      - uses: ./.github/actions/native-build
