name: common-java

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ZOWE_ROBOT_TOKEN }}
      - uses: ./.github/actions/native-build
        with:
          host: ${{ secrets.SSH_MARIST_RACF_HOST }}
          username: ${{ secrets.SSH_MARIST_USERNAME }}
          passwd: ${{ secrets.SSH_MARIST_RACF_PASSWORD }}

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: install zowe/cli
        run: npm install -g @zowe/cli@6.40.23
      - name: install zowe-api-dev
        run: npm -g install @zowedev/zowe-api-dev

      - name: Release or snapshot
        run: |
          ./gradlew publish -x test -Pzowe.deploy.username=$ARTIFACTORY_USERNAME -Pzowe.deploy.password=$ARTIFACTORY_PASSWORD -Partifactory_user=$ARTIFACTORY_USERNAME -Partifactory_password=$ARTIFACTORY_PASSWORD
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}